name: "sudo"
version: "0.0.1"
usage: "Helm sudo impersonate admin"
description: |-
  "Helm plugin that uses impersonating to execute helm-commands on clusters within the admin context"
command: "$HELM_PLUGINS/helm-sudo/run.sh"
useTunnel: false
ignoreFlags: false
hooks:
  install: "$HELM_PLUGINS/helm-sudo/install.sh"
  update: "$HELM_PLUGINS/helm-sudo/install.sh"